name: Last commit build
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run tests
        run: ./gradlew clean test
        shell: bash